"""add notifi model

Revision ID: 5ac894e04ceb
Revises: 51e73bd63959
Create Date: 2022-03-11 09:53:51.450671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac894e04ceb'
down_revision = '51e73bd63959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
